assert_lefthook_installed: true

pre-commit:
  parallel: true
  commands:
    {%- if cookiecutter.use_precommit %}
    pre-commit:
      run: pre-commit run --files {staged_files}
      stage_fixed: true
    {% endif -%}
    lint:
      glob: "*.go"
      run: golangci-lint run --fix {staged_files}
      stage_fixed: true
