name: Black

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version to use
      - uses: psf/black@stable
