name: Black

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
