name: Black

on:
  push:
    branches-ignore:
      - 'rt-**'    # ignore rapid-testing branches
      - 'docs**'  # ignore docs branch(es)
  pull_request:
    types: [ opened, reopened ]
    branches-ignore:
      - 'rt-**'
      - 'docs**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2
      - uses: psf/black@stable